version: '3.3'

services:
   postgresql:
      image: kartoza/postgis:11.0-2.5
      volumes:
        - ./deps/postgresql/data:/var/lib/postgresql
        - ./data:/data
      ports:
        - "25433:5432"
      environment:
         - USERNAME=docker
         - PASS=docker
         - ALLOW_IP_RANGE=0.0.0.0/0
      restart: on-failure

   gdal:
      image: osgeo/gdal:alpine-normal-3.0.3
      volumes:
        - ./data:/data

   trainer:
      image: continuumio/anaconda3:2021.11
      user: ${UID_GID}
      volumes:
        - ./data:/data
        - .:/app
