version: '3.3'

services:
   postgresql:
      image: postgis/postgis:14-3.2-alpine
      volumes:
        - ./deps/postgresql/data:/var/lib/postgresql/data
        - ./data:/data
      ports:
        - "25433:5432"
      environment:
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=gis
      restart: on-failure

   gdal:
      image: osgeo/gdal:ubuntu-small-3.4.2
      volumes:
        - ./data:/data

   trainer:
      image: continuumio/anaconda3:2021.11
      user: ${UID_GID}
      volumes:
        - ./data:/data
        - .:/app
